### ISSUE TITLE
Examples of configuration?

### ISSUE THREAD

**Issue by iaanus** [kanboard/plugin-reverse-proxy-ldap#1]
Configuring a Reverse Proxy is not an easy task. Although it's outside the scope of the plugin to provide an extensive setup guide, a couple of examples in the documentation would greatly help.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
