### ISSUE TITLE
REVERSE_PROXY_AUTH must be set to false (or unset)

### ISSUE THREAD

**Issue by dani** [kanboard/plugin-reverse-proxy-ldap#2]
The documentation of this plugin states:

You don't need to set to true those constants: LDAP_AUTH and REVERSE_PROXY_AUTH

But it's more than that. For LDAP_AUTH it's not important, but REVERSE_PROXY_AUTH must not be set (or be set to false), otherwise, no LDAP lookup will happen, only the proxy auth will be done

**Comment by dani** [comment]
BTW, another small point in the doc: LDAP_BIND_TYPE can also be set to anonymous. The important thing is just that it must not be set to user (obviously, as the user password is never seen by kanboard)

**Comment by fguillot** [comment]
Thank you, I updated the readme based on your feedback.
